#pragma once

#define NOMINMAX

#include <cstdint>
#include <cstddef>
#include <type_traits>
#include <utility>
#include <functional>
#include <memory>
#include <tuple>
#include <vector>
#include <algorithm>
#include <gsl/gsl>
#include <optional>
#include <string_view>
#include <string>
#include <chrono>
#include <filesystem>
#include <wrl/client.h>
#include <variant>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <string>
#include <array>
#include <boost/container/static_vector.hpp>
#include <boost/container_hash/hash.hpp>
#include <boost/unordered/unordered_map.hpp>
#include <fmt/format.h>
#include "DXDef.hpp"
#include "EasyDx.Common/One.hpp"
